## Prueba de  la red

In [1]:
import cv2

In [2]:
import tensorflow as tf
#import keras
import numpy as np
#from keras import backend as K
#K.tensorflow_backend._get_available_gpus()

In [3]:
def prepare(filepath):
    IMG_SIZE = 50  # 50 in txt-based
    img_array = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)  # read in the image, convert to grayscale
    new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))  # resize image to match model's expected sizing
    return new_array.reshape(1, IMG_SIZE, IMG_SIZE, 1).astype(float)/255.0  # return the image with shaping that TF wants.
    #(self.features.astype(float)/ 255.0)
#Next, we want to load our model:

In [4]:
#model = tf.keras.models.load_model("model.Aveztruz")
#model = tf.keras.models.load_model("model.Jirafa")
#model = tf.keras.models.load_model("model.Cuyo")
#model = tf.keras.models.load_model("model.Pinguino"
model = tf.keras.models.load_model("model.Hipopotamo")


Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [5]:
CATEGORIES =['NO es','Si es']

In [6]:
#predictiona = model.predict([prepare('./control/a_Hipo.jpg')])
#print(predictiona)  # will be a list in a list.
#print("No Conejo",predictiona[0][0])
#print("conejo",predictiona[0][1])
#print(CATEGORIES[int(predictiona[0][0])])

#max = np.argmax(predictiona)
#result = CATEGORIES[max]
#print(result)
#result = "Men: "+str(predictiona[0][0])+"% women: "+str(predictiona[0][1])+"%"
#plt.title(result)
#printable = pre.visioned_image(img)
#plt.imshow(printable)
    #plt.savefig(img+".png")

In [7]:
prediction = model.predict([prepare('./control/a_Hipo.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.10291104 0.89708894]]
Si es


In [8]:
prediction = model.predict([prepare('./control/aa_Hipo.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.03682953 0.96317047]]
Si es


In [9]:
prediction = model.predict([prepare('./control/b_Hipo.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.17840712 0.82159287]]
Si es


In [10]:
prediction = model.predict([prepare('./control/c_Hipo.png')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.03965582 0.96034414]]
Si es


In [11]:
prediction = model.predict([prepare('./control/d_Pingu.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.77405584 0.22594413]]
NO es


In [12]:
prediction = model.predict([prepare('./control/e_Pingu.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.8244524  0.17554761]]
NO es


In [13]:
prediction = model.predict([prepare('./control/f_Pingu.png')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[9.9999976e-01 2.2683651e-07]]
NO es


In [14]:
prediction = model.predict([prepare('./control/g_Cuyo.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.5728625  0.42713743]]
NO es


In [15]:
prediction = model.predict([prepare('./control/h_Cuyo.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.8876415  0.11235847]]
NO es


In [16]:
prediction = model.predict([prepare('./control/i_Cuyo.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.19155888 0.8084411 ]]
Si es


In [17]:
prediction = model.predict([prepare('./control/j_avez.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.99258053 0.00741938]]
NO es


In [18]:
prediction = model.predict([prepare('./control/jj_avez.jfif')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[9.9997699e-01 2.2977389e-05]]
NO es


In [19]:
prediction = model.predict([prepare('./control/k_avez.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.27653402 0.723466  ]]
Si es


In [20]:
prediction = model.predict([prepare('./control/kk_avez.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.5395881  0.46041194]]
NO es


In [21]:
prediction = model.predict([prepare('./control/l_avez.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.2758711 0.7241289]]
Si es


In [22]:
prediction = model.predict([prepare('./control/m_jira.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.87358254 0.12641747]]
NO es


In [23]:
prediction = model.predict([prepare('./control/n_jira.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.39995003 0.60005003]]
Si es


In [24]:
prediction = model.predict([prepare('./control/o_jira.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.7411353 0.2588647]]
NO es


In [25]:
prediction = model.predict([prepare('./control/w_Libro.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.90208    0.09792004]]
NO es


In [26]:
prediction = model.predict([prepare('./control/x_Conejo.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.47245765 0.52754235]]
Si es


In [27]:
prediction = model.predict([prepare('./control/y_Perro.png')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.9374152  0.06258484]]
NO es


In [28]:
prediction = model.predict([prepare('./control/z_Conejo.jpg')])
print(prediction)  # will be a list in a list.
max = np.argmax(prediction)
result = CATEGORIES[max]
print(result)

[[0.9658291  0.03417092]]
NO es


In [29]:
#decode_predictions(prediction)

In [30]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 46, 46, 16)        416       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 42, 42, 32)        12832     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 21, 21, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 19, 19, 64)        18496     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 17, 17, 64)        36928     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 8, 8, 64)          0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 6, 6, 128)         7

In [31]:
#import matplotlib.pyplot as plt #vizualizacion grafica como cybog

In [32]:
prediction

array([[0.9658291 , 0.03417092]], dtype=float32)

In [33]:
print("Termino")

Termino
